modLoader = "javafml" #mandatory
loaderVersion = "[${forgeshortversion},)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "All rights reserved"
issueTrackerURL = "https://github.com/FTBTeam/FTB-Mods-Issues/issues" #optional
[[mods]] #mandatory
modId = "ftbic" #mandatory
version = "${version}" #mandatory
displayName = "FTB Industrial Contraptions" #mandatory
authors = "FTB"
description = '''
FTB Industrial Contraptions
'''

[[dependencies.ftbic]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[${forgeversion},)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbic]]
modId = "minecraft"
mandatory = true
versionRange = "[${mcversion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ftbic]]
modId = "architectury"
mandatory = true
versionRange = "[${archversion},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbic]]
modId = "ftblibrary"
mandatory = true
versionRange = "[${ftblibversion},)"
ordering = "AFTER"
side = "BOTH"

#[[dependencies.ftbic]]
#modId = "emendatusenigmatica"
#mandatory = false
#versionRange = "[1,)"
#ordering = "AFTER"
#side = "BOTH"
